#ifndef COMMONMESSAGEHANDLER_GLOBAL_H
#define COMMONMESSAGEHANDLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMONMESSAGEHANDLER_LIBRARY)
#  define COMMONMESSAGEHANDLER_EXPORT Q_DECL_EXPORT
#else
#  define COMMONMESSAGEHANDLER_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMONMESSAGEHANDLER_GLOBAL_H
